- name: Setup RoboShop Frontend
  hosts: frontend
  become: yes

  vars:
    frontend_zip_url: "https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip"
    frontend_dest: "/usr/share/nginx/html"


  tasks:

    - name: Disable old nginx module
      ansible.builtin.command: dnf module disable nginx -y

    - name: Enable nginx 1.24 module
      ansible.builtin.command: dnf module enable nginx:1.24 -y

    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Start and enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Remove default nginx content
      ansible.builtin.file:
        path: "{{ frontend_dest }}/*"
        state: absent
        recurse: yes

    - name: Download frontend zip
      ansible.builtin.get_url:
        url: "{{ frontend_zip_url }}"
        dest: /tmp/frontend.zip

    - name: Install unzip package
      ansible.builtin.dnf:
        name: unzip
        state: present

    - name: Extract frontend content
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: "{{ frontend_dest }}"
        remote_src: yes

    - name: Create Nginx reverse proxy configuration
      ansible.builtin.copy:
        dest: /etc/nginx/nginx.conf
        content: |
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log notice;
          pid /run/nginx.pid;

          include /usr/share/nginx/modules/*.conf;

          events {
              worker_connections 1024;
          }

          http {
              log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for"';

              access_log  /var/log/nginx/access.log  main;

              sendfile            on;
              tcp_nopush          on;
              keepalive_timeout   65;
              types_hash_max_size 4096;

              include             /etc/nginx/mime.types;
              default_type        application/octet-stream;

              include /etc/nginx/conf.d/*.conf;

              server {
                  listen       80;
                  listen       [::]:80;
                  server_name  _;
                  root         /usr/share/nginx/html;

                  include /etc/nginx/default.d/*.conf;

                  error_page 404 /404.html;
                  location = /404.html { }

                  error_page 500 502 503 504 /50x.html;
                  location = /50x.html { }

                  location /images/ {
                    expires 5s;
                    root   /usr/share/nginx/html;
                    try_files $uri /images/placeholder.jpg;
                  }

                  location /api/catalogue/ { proxy_pass http://{{  catalogue.sndp.online }}:8080/; }
                  location /api/user/ { proxy_pass http://{{  user.sndp.online }}:8080/; }
                  location /api/cart/ { proxy_pass http://{{  cart.sndp.online }}:8080/; }
                  location /api/shipping/ { proxy_pass http://{{  shipping.sndp.online }}:8080/; }
                  location /api/payment/ { proxy_pass http://{{  payment.sndp.online }}:8080/; }

                  location /health {
                    stub_status on;
                    access_log off;
                  }

              }
          }

    - name: Restart nginx to load new configuration
      ansible.builtin.service:
        name: nginx
        state: restarted
