---
- name: Install specific MongoDB version with role
  hosts: mongodb
  become: yes

  roles:
    - trfore.mongodb_install

  tasks:

    - name: Download MongoDB GPG key
      shell: |
        curl -fsSL https://pgp.mongodb.com/server-7.0.asc \
        | gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg
      args:
        creates: /usr/share/keyrings/mongodb-server-7.0.gpg  

   
    - name: Prepare python correctly
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Configure MongoDB bind IP
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Enable and start MongoDB
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
