---
- name: Install MongoDB 7.0 on RHEL 9
  hosts: mongodb
  become: yes

  tasks:

    - name: Add MongoDB 7.0 YUM repository
      ansible.builtin.yum_repository:
        name: mongodb-org-7.0
        description: MongoDB Repository
        baseurl: https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
        gpgcheck: yes
        enabled: yes
        gpgkey: https://pgp.mongodb.com/server-7.0.asc

    - name: Install MongoDB packages
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: Configure MongoDB to listen on all interfaces
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Enable and start MongoDB
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
