---
- name: Install specific MongoDB version with role
  hosts: mongodb
  become: yes

  vars:
    mongodb_version: "7.0.12"

  roles:
    - trfore.mongodb_install

  tasks:
    - name: configuring the ip public_ip_address
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0

    - name: enabling the mongo-db
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
