- name: installing Mongodb
  hosts: mongodb
  become : yes

  tasks:
    - name: Add MongoDB GPG key
      ansible.builtin.apt_key:
        url: https://www.mongodb.org/static/pgp/server-7.0.asc
        state: present

    - name: Add MongoDB repository
      ansible.builtin.apt_repository:
        repo: "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse"
        state: present

    - name: install mongo-db
      ansible.builtin.apt:
        name: mongodb-org
        state: present

    - name: configuring the ip public_ip_address
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0

    - name: enabling the mongo-db
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
