- name: installing mysql server 
  hosts: mysql
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

   
    - name: installing mysql
      ansible.builtin.apt:
        name: mysql-server
        state: present
