- name: installing mysql server 
  hosts: mysql
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

   
    - name: installing mysql
      ansible.builtin.apt:
        name: mysql-server
        state: present


    - name: enabling the mysql
      ansible.builtin.service:
        name: mysql-server
        state: started
        enabled: yes
