- name: Install and configure Payment service
  hosts: payment
  become: yes

  vars:
    app_user: roboshop
    app_dir: /app
    cart_host: "<CART-SERVER-IPADDRESS>"
    cart_port: 8080
    user_host: "<USER-SERVER-IPADDRESS>"
    user_port: 8080
    amqp_host: "<RABBITMQ-SERVER-IPADDRESS>"
    amqp_user: roboshop
    amqp_pass: roboshop123

  tasks:

    - name: Install Python 3 and dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python3-dev
          - gcc
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Create application system user
      ansible.builtin.user:
        name: "{{ app_user }}"
        system: yes
        home: "{{ app_dir }}"
        shell: /sbin/nologin
        comment: "roboshop system user"

    - name: Create application directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: Download catalogue zip using curl
      ansible.builtin.command: curl -sL https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip -o /tmp/payment.zip
      become: yes

    - name: Unzip Payment application
      ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: "{{ app_dir }}"
        remote_src: yes
        owner: "{{ app_user }}"
        group: "{{ app_user }}"

    - name: Install Python dependencies from requirements.txt
      ansible.builtin.pip:
        requirements: "{{ app_dir }}/requirements.txt"
        executable: pip3
        extra_args: "--break-system-packages"

    - name: Create systemd service file for Payment
      ansible.builtin.copy:
        dest: /etc/systemd/system/payment.service
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=Payment Service

          [Service]
          User={{ app_user }}
          WorkingDirectory={{ app_dir }}
          Environment=CART_HOST={{ cart_host }}
          Environment=CART_PORT={{ cart_port }}
          Environment=USER_HOST={{ user_host }}
          Environment=USER_PORT={{ user_port }}
          Environment=AMQP_HOST={{ amqp_host }}
          Environment=AMQP_USER={{ amqp_user }}
          Environment=AMQP_PASS={{ amqp_pass }}
          ExecStart=/usr/local/bin/uwsgi --ini payment.ini
          ExecStop=/bin/kill -9 $MAINPID
          SyslogIdentifier=payment

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start Payment service
      ansible.builtin.service:
        name: payment
        state: started
        enabled: yes
