- name: installing Rabitmq
  hosts: Rabitmq
  become: yes

  vars:
    rabbitmq_user: roboshop
    rabbitmq_password: roboshop123



  tasks:

 


   
    

 

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Erlang (required for RabbitMQ)
    apt:
      name: erlang
      state: present

  - name: Install RabbitMQ server
    apt:
      name: rabbitmq-server
      state: present

  - name: Enable and start RabbitMQ service
    systemd:
      name: rabbitmq-server
      enabled: yes
      state: started

  - name: Add RabbitMQ user
    command: rabbitmqctl add_user {{ rabbitmq_user }} {{ rabbitmq_password }}
    args:
      creates: "/var/lib/rabbitmq/.{{ rabbitmq_user }}"   # Optional: prevent re-running

  - name: Set permissions for RabbitMQ user
    command: rabbitmqctl set_permissions -p / {{ rabbitmq_user }} ".*" ".*" ".*"


