- name: installing redis
  hosts : redis
  become: yes


  tasks:

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Update apt cache
    ansible.builtin.command: apt update
      

  - name: installing redis package
    ansible.builtin.apt:
      name: redis-server
      state : present


  

  - name: enabling the catalogue
    ansible.builtin.service:
      name: catalogue.service
      state: started
      enabled: yes
