- name: installing redis
  hosts : redis
  become: yes


  tasks:

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Update apt cache
    ansible.builtin.command: apt update
      

  - name: installing redis package
    ansible.builtin.apt:
      name: redis-server
      state : present


  

  - name: enabling the redis
    ansible.builtin.service:
      name: redis-server
      state: started
      enabled: yes


  - name: Replacing the ports
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  
  - name: Change protected-mode to no
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: '5686protected-mode'
      line: 'protected-mode no'
      backup: yes

  - name: Restart Redis
    ansible.builtin.service:
      name: redis-server
      state: restarted