- name: creating ec2-user and update route-53
  hosts: local
  connection: local

  vars:
    region: us-east-1
    ami_id: ami-0b6c6ebed2801a5cb   # Ubuntu AMI (change this!)
    instance_type: t3.micro
    key_name: ubuntu-key
    security_group: sg-0eae84a28840ffd0c
    subnet_id: subnet-0966e58e0745048a2
    domain : sndp.online
    env: dev
    instances:
      - mongo
      - catalouge
      - frontend
      - user
      - cart
      - redis
      - mysql
      - frontend

  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        wait: yes
        region: "{{ region }}"
        security_group: "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"
        name: "{{item}}-{{env}}"
        tags:
          Project : Roboshop
          Env: dev
          name: "{{item}}-{{env}}"
        network:
          assign_public_ip: true
      
      loop : "{{instances}}"
      register:  ec2_output


    - name: printing the ec2 output
      ansible.builtin.debug:
        msg: "{{ec2_output}}"


    - name: creating route 53 record 
      amazon.aws.route53:
        state: present
        zone: "{{domain}}"
        record: "{{item.item}}-{{env}}.{{domain}}"
        type: A
        ttl: 2
        value: "{{item.instances[0].private_ip_address}}"
        overwrite: true
        wait: true     
      loop: "{{ec2_output.results}}"


    - name: creating route 53 record for frontend
      amazon.aws.route53:
        state: present
        zone: "{{domain}}"
        record: "roboshop-{{ env }}.{{ domain }}"   #item.item --> mongo , catalougr 
        type: A
        ttl: 2
        value: "{{item.instances[0].public_ip_address}}"
        overwrite: true
        wait: true 
        
      
      loop: "{{ec2_output.results}}"

      when:
        - item.item == "frontend"
      






