- name: creating ec2-user and update route-53
  hosts: local
  connection: local


  tasks:
    - naame :  verifyig it is working 
      ansible.builtin.debug:
        msg : "Local host is working "
      